name: Better Business Bandit
favicon: null
layout_spectrum: 0.2803395420778543
typography_spectrum: 0.8298428340349346
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-38015203-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#341b38'
    - '#3b79b2'
    - '#862d3f'
    - '#e6dc60'
    - '#c59b73'
  brandStrength: 0.5625
  lightness: 0.40011503268033266
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
