name: Jakub Dubec
favicon: null
layout_spectrum: 0.2803395420778543
typography_spectrum: 0.8298428340349346
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-38015203-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.6345542434137315
  lightness: 0.40011503268033266
  saturation: 0.21717689419165254
  rhythmicContrast: 0.3326289828401059
purpose: []
