name: Better Business Bandit
favicon: null
layout_spectrum: 0.9923
typography_spectrum: 0.8298428340349346
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-38015203-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a1a18'
    - '#fe8800'
    - '#82b500'
    - '#d7e5a8'
    - '#00ae71'
  brandStrength: 0.125
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
